CREATE TABLE [dbo].[Audit_Dspec] (
  [AuditId] bigint IDENTITY(1, 1) NOT NULL,
  [ID] bigint NOT NULL,
  [ORDER_NUM] smallint NOT NULL,
  [ARTICLE_ID] smallint NOT NULL,
  [QTY] decimal(18, 3) NOT NULL,
  [PRICE_ECO] decimal(18, 6) NULL,
  [DOC_DATE] smalldatetime NOT NULL,
  [DOC_TYPE_ID] int NULL,
  [DHEAD_ID] [DtFkey] NOT NULL,
  [ENTITY_TYPE] [DtCode] NOT NULL,
  [IS_FRACTION] char(1) COLLATE Cyrillic_General_CI_AS NOT NULL,
  [OUR_FIRM_ID] int NOT NULL,
  [PRICE_ECO_IN] decimal(18, 6) NULL,
  [DEPT_ID] [DtFkey] NULL,
  [CONTRACTOR_ID] [DtFkey] NULL,
  [QTY_PAY] decimal(18, 3) NULL,
  [QTY_FIRST] decimal(18, 3) NULL,
  [CreateUser] smallint NULL,
  [LastEditUser] smallint NULL,
  [blank_id] int NULL,
  [NaklNo] int NULL,
  [CONTRACTOR_ACC_ID] [DtFkey] NOT NULL,
  [MANAGER_DEPT_ID] [DtFkey] NULL,
  [STATE_ID] [DtFkey] NOT NULL,
  [OUT_TRADE_ID] [DtFkey] NULL,
  [TRIP_ID] [DtFkey] NULL,
  [QTY_FIT] decimal(18, 3) NULL,
  [MANAGER_ID] [DtFkey] NULL,
  [row_version] [DtInteger] NULL,
  [PRICE_TYPE_ID] [DtFkey] NULL,
  [Edit_date] datetime NOT NULL,
  [Edit_user] varchar(50) COLLATE Cyrillic_General_CI_AS NOT NULL,
  [Edit_host_name] varchar(50) COLLATE Cyrillic_General_CI_AS NOT NULL,
  [Action_type] char(1) COLLATE Cyrillic_General_CI_AS NOT NULL
)
ON [PRIMARY]
GO