CREATE TABLE [dbo].[Audit_NaklR] (
  [Audit_id] int IDENTITY(1, 1) NOT NULL,
  [NaklNo] int NOT NULL,
  [Nom] int NULL,
  [NomFirst] varchar(10) COLLATE Cyrillic_General_CI_AS NULL,
  [NomReturn] [DtFkey] NULL,
  [PostNo] smallint NOT NULL,
  [PostNoFirst] smallint NULL,
  [PostNoReturn] smallint NULL,
  [DateNakl] smalldatetime NOT NULL,
  [DateNaklFirst] smalldatetime NULL,
  [Summa] decimal(18, 2) NULL,
  [SummaDolg] decimal(18, 2) NULL,
  [SotrudNo] smallint NULL,
  [DateOpl] smalldatetime NULL,
  [RealDateOpl] smalldatetime NULL,
  [Buh] smallint NOT NULL,
  [VidNaklNo] smallint NOT NULL,
  [UserNo] smallint NULL,
  [ColnPrice] smallint NULL,
  [Ask] bit NOT NULL,
  [AddressNo] smallint NULL,
  [ExpeditionNo] int NULL,
  [Weight] decimal(10, 3) NULL,
  [KolPerPak] decimal(10, 3) NULL,
  [InCar] bit NOT NULL,
  [Change1C] bit NULL,
  [Export1C] bit NULL,
  [ID1C] varchar(6) COLLATE Cyrillic_General_CI_AS NULL,
  [OtdelNo] smallint NULL,
  [Svedenie] bit NULL,
  [is_check_first] bit NULL,
  [id] int NULL,
  [AddressNoFirst] smallint NULL,
  [contract_id] int NULL,
  [edit_status_id] smallint NOT NULL,
  [description] varchar(1024) COLLATE Cyrillic_General_CI_AS NULL,
  [OurFirmNo] int NOT NULL,
  [dept_id] int NULL,
  [num] varchar(128) COLLATE Cyrillic_General_CI_AS NULL,
  [sub_num] int NULL,
  [doc_type_id] int NULL,
  [pkey] [DtPkey] NOT NULL,
  [SET_ARTICLE_GROUP_ID] [DtFkey] NULL,
  [Edit_date] datetime NOT NULL,
  [Edit_user] varchar(50) COLLATE Cyrillic_General_CI_AS NOT NULL,
  [Edit_host_name] varchar(50) COLLATE Cyrillic_General_CI_AS NOT NULL,
  [Action_type] char(1) COLLATE Cyrillic_General_CI_AS NOT NULL
)
ON [PRIMARY]
GO

EXEC sp_bindefault '[dbo].[DefDtPkey]', '[Audit_NaklR].[pkey]'
GO